### PR TITLE
Added descriptions to the contribution guidelines

### PR DESCRIPTION
**Pull request by tommysdk**

### CODE REVIEW

**Comment by tommysdk** [comment]
@jesperps what do you think?

**Comment by jesperps** [comment]
@tommysdk Nice, but it would be a little nicer if the last step (Add a link to the pull request to the associated Jira issue) was a substep to previous one (Create a pull request to get feedback from the maintainers) I.e:
- Create a pull request to get feedback from the maintainers
  - Be sure to add a link to the pull request to the associated Jira issue

**Comment by jesperps** [comment]
Should I merge and update according to my suggestion or do you want to make the updates before I merge or do you think the update is unnecessary?

**Comment by tommysdk** [comment]
@jesperps If you merge my pull request to your branch the original pull request should be updated. Then you can make your suggested adjustment (which I think is good). Then we should be good to go (merge).

**Pull request merged**
